# Generated by Django 5.1.2 on 2024-12-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(default='write bio here', max_length=100),
            preserve_default=False,
        ),
    ]
