# Generated by Django 5.1.2 on 2025-01-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0002_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='phone number', max_length=100),
        ),
    ]
