# Generated by Django 5.1.2 on 2025-01-04 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_vendor_product_vendor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='product_status',
            field=models.CharField(choices=[('delivered', 'Delivered'), ('processing', 'Processing'), ('shipped', 'Shipped')], default='processing', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('disabled', 'Disabled'), ('in_review', 'In_review'), ('rejected', 'Rejected'), ('published', 'Published'), ('draft', 'Draft')], default='in_review', max_length=10),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(4, '★★★★☆'), (5, '★★★★★'), (2, '★★☆☆☆'), (1, '★☆☆☆☆'), (3, '★★★☆☆')], default=None),
        ),
    ]
