# Generated by Django 5.1.2 on 2025-01-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_cartorder_product_status_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('rejected', 'Rejected'), ('disabled', 'Disabled'), ('in_review', 'In_review'), ('draft', 'Draft'), ('published', 'Published')], default='in_review', max_length=10),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(3, '★★★☆☆'), (4, '★★★★☆'), (5, '★★★★★'), (1, '★☆☆☆☆'), (2, '★★☆☆☆')], default=None),
        ),
    ]
