# Generated by Django 5.1.2 on 2025-01-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_product_product_status_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='product_status',
            field=models.CharField(choices=[('shipped', 'Shipped'), ('delivered', 'Delivered'), ('processing', 'Processing')], default='processing', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('in_review', 'In_review'), ('published', 'Published'), ('rejected', 'Rejected'), ('disabled', 'Disabled'), ('draft', 'Draft')], default='in_review', max_length=10),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(2, '★★☆☆☆'), (3, '★★★☆☆'), (5, '★★★★★'), (4, '★★★★☆'), (1, '★☆☆☆☆')], default=None),
        ),
    ]
