# Generated by Django 5.1.2 on 2025-01-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_product_product_status_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('published', 'Published'), ('in_review', 'In_review'), ('rejected', 'Rejected'), ('draft', 'Draft'), ('disabled', 'Disabled')], default='in_review', max_length=10),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, '★☆☆☆☆'), (3, '★★★☆☆'), (5, '★★★★★'), (4, '★★★★☆'), (2, '★★☆☆☆')], default=None),
        ),
    ]
