# Generated by Django 5.1.2 on 2025-01-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_product_product_status_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='product_status',
            field=models.CharField(choices=[('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='processing', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('rejected', 'Rejected'), ('disabled', 'Disabled'), ('published', 'Published'), ('in_review', 'In_review')], default='in_review', max_length=10),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(5, '★★★★★'), (3, '★★★☆☆'), (4, '★★★★☆'), (2, '★★☆☆☆'), (1, '★☆☆☆☆')], default=None),
        ),
    ]
